package com.nine.back.entity;

public class AdminUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.USERNAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.PASSWORD
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.REALNAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.RETRY
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Short retry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.STATUS
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.CREATEDATE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Long createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.LASTDATE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Long lastdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_user.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String rolecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.ID
     *
     * @return the value of t_admin_user.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.ID
     *
     * @param id the value for t_admin_user.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.USERNAME
     *
     * @return the value of t_admin_user.USERNAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.USERNAME
     *
     * @param username the value for t_admin_user.USERNAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.PASSWORD
     *
     * @return the value of t_admin_user.PASSWORD
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.PASSWORD
     *
     * @param password the value for t_admin_user.PASSWORD
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.REALNAME
     *
     * @return the value of t_admin_user.REALNAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.REALNAME
     *
     * @param realname the value for t_admin_user.REALNAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.RETRY
     *
     * @return the value of t_admin_user.RETRY
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Short getRetry() {
        return retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.RETRY
     *
     * @param retry the value for t_admin_user.RETRY
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRetry(Short retry) {
        this.retry = retry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.STATUS
     *
     * @return the value of t_admin_user.STATUS
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.STATUS
     *
     * @param status the value for t_admin_user.STATUS
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.CREATEDATE
     *
     * @return the value of t_admin_user.CREATEDATE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Long getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.CREATEDATE
     *
     * @param createdate the value for t_admin_user.CREATEDATE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.LASTDATE
     *
     * @return the value of t_admin_user.LASTDATE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Long getLastdate() {
        return lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.LASTDATE
     *
     * @param lastdate the value for t_admin_user.LASTDATE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setLastdate(Long lastdate) {
        this.lastdate = lastdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_user.ROLECODE
     *
     * @return the value of t_admin_user.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_user.ROLECODE
     *
     * @param rolecode the value for t_admin_user.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }
}