package com.nine.back.entity;

public class AdminRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role.ROLENAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role.ID
     *
     * @return the value of t_admin_role.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role.ID
     *
     * @param id the value for t_admin_role.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role.ROLECODE
     *
     * @return the value of t_admin_role.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role.ROLECODE
     *
     * @param rolecode the value for t_admin_role.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role.ROLENAME
     *
     * @return the value of t_admin_role.ROLENAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role.ROLENAME
     *
     * @param rolename the value for t_admin_role.ROLENAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}