package com.nine.back.entity;

public class AdminResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.RID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.PID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.NAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.URL
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.LEAF
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer leaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.STATUS
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.ORDERID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_resources.ICON
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.ID
     *
     * @return the value of t_admin_resources.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.ID
     *
     * @param id the value for t_admin_resources.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.RID
     *
     * @return the value of t_admin_resources.RID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.RID
     *
     * @param rid the value for t_admin_resources.RID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.PID
     *
     * @return the value of t_admin_resources.PID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.PID
     *
     * @param pid the value for t_admin_resources.PID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.NAME
     *
     * @return the value of t_admin_resources.NAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.NAME
     *
     * @param name the value for t_admin_resources.NAME
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.URL
     *
     * @return the value of t_admin_resources.URL
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.URL
     *
     * @param url the value for t_admin_resources.URL
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.LEAF
     *
     * @return the value of t_admin_resources.LEAF
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.LEAF
     *
     * @param leaf the value for t_admin_resources.LEAF
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setLeaf(Integer leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.STATUS
     *
     * @return the value of t_admin_resources.STATUS
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.STATUS
     *
     * @param status the value for t_admin_resources.STATUS
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.ORDERID
     *
     * @return the value of t_admin_resources.ORDERID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.ORDERID
     *
     * @param orderid the value for t_admin_resources.ORDERID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_resources.ICON
     *
     * @return the value of t_admin_resources.ICON
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_resources.ICON
     *
     * @param icon the value for t_admin_resources.ICON
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}