package com.nine.back.entity;

public class AdminRoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role_resource.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role_resource.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin_role_resource.RESOURCEID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    private Integer resourceid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role_resource.ID
     *
     * @return the value of t_admin_role_resource.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role_resource.ID
     *
     * @param id the value for t_admin_role_resource.ID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role_resource.ROLECODE
     *
     * @return the value of t_admin_role_resource.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role_resource.ROLECODE
     *
     * @param rolecode the value for t_admin_role_resource.ROLECODE
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin_role_resource.RESOURCEID
     *
     * @return the value of t_admin_role_resource.RESOURCEID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public Integer getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin_role_resource.RESOURCEID
     *
     * @param resourceid the value for t_admin_role_resource.RESOURCEID
     *
     * @mbggenerated Wed Apr 05 12:29:36 CST 2017
     */
    public void setResourceid(Integer resourceid) {
        this.resourceid = resourceid;
    }
}