package com.nine.back.mapper;

import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import com.nine.back.entity.AdminUser;

public interface AdminUserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin_user
	 *
	 * @mbggenerated Wed Apr 05 12:29:36 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin_user
	 *
	 * @mbggenerated Wed Apr 05 12:29:36 CST 2017
	 */
	int insert(AdminUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin_user
	 *
	 * @mbggenerated Wed Apr 05 12:29:36 CST 2017
	 */
	int insertSelective(AdminUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin_user
	 *
	 * @mbggenerated Wed Apr 05 12:29:36 CST 2017
	 */
	AdminUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin_user
	 *
	 * @mbggenerated Wed Apr 05 12:29:36 CST 2017
	 */
	int updateByPrimaryKeySelective(AdminUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin_user
	 *
	 * @mbggenerated Wed Apr 05 12:29:36 CST 2017
	 */
	int updateByPrimaryKey(AdminUser record);
	
	@Select("select ID from t_admin_user where USERNAME=#{userName}")
	@Result(column="ID",property="id")
	int getUserId(String userName);
	
	@Select("select ROLECODE from t_admin_user where USERNAME=#{userName}")
	String getRoleCodeByUserName(String userName);
	
	@Update("update t_admin_user set ROLECODE=#{0} where USERNAME=#{1}")
	void ChangeRoleCode(String rolecode,String username);	
}